### ISSUE TITLE
[Umbrella issue] Automate DNS for Kubernetes assets

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#151]
Please see:
- https://github.com/kubernetes/k8s.io/pull/139
- https://github.com/kubernetes/k8s.io/pull/147

Notes from meeting:

- [Aaron] Where are we on the roadmap
  - [Tim] Need 3 things: 1 - Tests with canaries. 2 - Figure out billing transparency. 3 - Alerts.
- [Aaron] Where does it run?
  -[Tim] - Google Cloud DNS
- [Aaron] Where is OctoDNS running?
  -[Tim] Manually / locally using a Docker build, until we have a cluster up and running on a regular basis.
  -[Tim] To make changes, PR those changes, and those with access to the GCP project approve and run OctoDNS
- [Brendan] Might need to track changes if people have to run it post PR merge.
- [Aaron] - We need some docs for process
- [Justin] - Can we automate this?
  - [Aaron] Maybe copy Prow process for k/org

**Comment by dims** [comment]
cc @justinsb @brendandburns @thockin @hh @spiffxp

**Comment by thockin** [comment]
Annotated TODOs from the README:

* Get owner names and comments on all records: Willing to proceed without full coverage of names

* Push an official image to GCR: thockin will do as soon as we are ready to go live

* When to rebuild?:  Not sure.  Maybe just leave it alone and update when we know we need to?  Low risk as long as pushes are manual.

* Implement the test part of the push script: Assigned to @hh (please confirm?).  @thockin is willing to do this if @hh can't get to it.

* Document how to handle "too many" updates (--force): Punt for now and cross that bridge when we get there
* Always --force?: (see above)

* Billing report: assigned to @idvoretskyi, but we should proceed without this (not a technical issue with the serving path) 

* Usage report: willing to proceed without this

* Monitoring / alerts / on-call: We have an alerts group, but we don't have any probes for DNS.  Could use a volunteer on this, but willing to proceed without it?

* Figure out who to contact to flip top-level NS records: thockin will do when we are ready


So the only outstanding issue is integrating a canary test in the push script.  @hh, ball is in your court.  If you want to punt the test, just say so.  Otherwise - eta for something we can start to discuss?

**Comment by hh** [comment]
Digging into two build in options:

https://github.com/github/octodns/blob/master/octodns/cmds/report.py
https://github.com/github/octodns/blob/master/octodns/cmds/compare.py

**Comment by hh** [comment]
@thockin if do you want to try and apply #162 using the new push/test scripts?

**Comment by spiffxp** [comment]
next steps?
- cluster?
- wait until prow?
- if someone files an issue, people in the OWNERS file can push a PR, once the PR is merged, "we = k8s-infra-dns-admins googlegroup" can run a command which canaries and pushes to prod

**Comment by spiffxp** [comment]
/close
I'm closing this as implemented well enough for proof of concept, and opened up #239 for followup work to automate this further such that it becomes self-service
