### ISSUE TITLE
24x7 k8s-infra on-call

### ISSUE THREAD

**Issue by moshloop** [kubernetes/k8s.io#1782]
Kubernetes is a global project and used in enough mission-critical environments that support non-prow-related issues should have 24x7 on-call rotation (activable by any Kubernetes member) with a primary and standby. 

What are the limitations that would prevent a call for volunteers to go out to augment the existing team that is doing their very best but are ultimately PST bound and providing support on a best-effort basis?

I know there was a call for general volunteers and I am not sure how successful that was, what I am referring to is a specific call for people to be added to an official on-call rotation (after meeting pre-determined criteria, vetting, and continued participation in the wg, etc.. )

@kubernetes/steering-committee

**Comment by thockin** [comment]
For what it's worth, I'd *love* to see this be more formalized.  But I agree with Aaron - it's not as simple as getting people to sign up.   This is a somewhat under-serviced WG right now.  We're incrementally, slowly, piece by piece getting better, but part of that is also revisiting prior decisions with new context. 

When it was just me editing the bash, it was fine.  Now that we have a) a lot more bash and b) more people modifying it, the shortcomings of that decision become clearer.

In addition to that, we don't have great "playbooks" in large part "because nobody has written them".  I can't, in good conscience,  ask people to take responsibility for that.  It has to start with people helping bootstrap the whole endeavour.

**Comment by moshloop** [comment]
Thanks for the feedback - I will draft a working document for discussion at the next meeting.

**Comment by moshloop** [comment]
Work in progress is here: https://docs.google.com/document/d/1ih_h-0qnX8B0VjtoE1a6YjF8VTimoZ1jm_U78wnyu0g/edit

**Comment by ameukam** [comment]
/remove-lifecycle rotten
lifecycle frozen

**Comment by ameukam** [comment]
I don't see any progress or any improvement regarding this. 

Closing for now.
/close
