### ISSUE TITLE
Moving Gcsweb to CNCF Infrastructure

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#204]
As one of the tasks is to moving Gcsweb to CNCF Infrastructure (https://docs.google.com/document/d/1r0nydnBoU7o_L7Hnjdc9SZrWe9zosbz64ZUUPn0XwXk)
I would like to take this task and work on it.

@thockin, @ixdy - could you maybe give me a hand with the issue?

**Comment by bartsmykla** [comment]
@spiffxp, @thockin, @ixdy  who should I poke to get some informations about cluster, where Gcsweb should be moved to (especially related to access)?

**Comment by dims** [comment]
/assign @thockin @ixdy 

Tim, Jeff, can you please pull the existing manifests and let @bartsmykla take a peek?

**Comment by ixdy** [comment]
The existing manifests are in the gcsweb.k8s.io/ directory of this repo, currently running in the same Kubernetes cluster that we run the k8s.io redirector (and to which I recently deployed cert-manager). It runs in the `gcsweb` namespace, but I don't think that's encoded in the checked-in manifests (for whatever reason).

We don't really have any turnup scripts or anything, though I think you'd run into trouble creating the ingress right now due to https://github.com/jetstack/cert-manager/issues/1343. I guess if we update to cert-manager 0.7 that shouldn't be an issue, though.

I don't know where this would run in CNCF infrastructure.

**Comment by thockin** [comment]
We need to get the "real" cluster up in the next few weeks.  Not much
you can really do until then, sadly.

**Comment by dims** [comment]
needs a cluster

**Comment by thockin** [comment]
DONE
