### ISSUE TITLE
Infra request for new testgrid monitoring system 

### ISSUE THREAD

**Issue by rajula96reddy** [kubernetes/k8s.io#3071]
Hello,

The CI Signal Release team for 1.23 has been working on improving monitoring for [testgrid](testgrid.k8s.io/) from a release perspective and as a part of it, @encodeflush developed a [testgrid exporter](https://github.com/encodeflush/testgrid-json-exporter) that scrapes Prometheus compatible metrics from Testgrid, which can be used to setup Prometheus alerts and also visualize with Grafana (or similar tool). This will help the release team to quickly visualize the status of the jobs and take actions accordingly.

For the same, we would like to initiate a discussion on how we can deploy it on the community infrastructure.

Ref: https://github.com/orgs/kubernetes/projects/65#card-72753740

CC: @kubernetes/ci-signal

**Comment by ameukam** [comment]
cc @spiffxp 

/sig release
/area release-eng

**Comment by leonardpahlke** [comment]
@ameukam how should be proceed with this issue? The project/infrastructure setup seems to be ready to get donated, merged and deployed - @encodeflush can you confirm?

**Comment by ameukam** [comment]
@leonardpahlke Do we have a clarification about ownership of the monitoring platform ? AFAIK the CI signal is subject to rotation. 

If you want to move forward with this issue, you can start with : https://github.com/kubernetes/k8s.io/blob/main/running-in-community-clusters.md.

**Comment by leonardpahlke** [comment]
> Do we have a clarification about ownership of the monitoring platform ?

No, I assume this will be similar to the ci-reporter CLI (in k/release) with the current CI Signal team as owners (reviewers). I can put this on the next release engineering agenda for clarification.

**Comment by puerco** [comment]
My take on this is that we could officially assign ownership to the release engineering group, but then delegate the effective responsibility to the rotating CI signal team as they will be the primary operators.

The data is really important, but I think it is not super critical to ensure a delivery time with 99.99999% accuracy.  So while it would imply being _on call_, it is not really a burden that will get you paged at 4 am. So even if CI Signal members do not have direct access to fix things, release managers are distributed globally so there would be always someone available to help.

**Comment by leonardpahlke** [comment]
FYI, there is currently a discussion about improving the reliability of Kubernetes, see https://github.com/kubernetes/enhancements/pull/3139 Depending on the outcome of the discussion, the CI Signal team might be responsible for doing this. On the sidelines of this discussion, a dashboard - sippy (see [repo](https://github.com/openshift/sippy)) was discussed to track job history.

Since this issue discusses how we can improve CI Signal's day-to-day work by introducing a new, simple "one-page" dashboard, we should think about how this might interact if sippy is part of the tool set and reliability is a key factor for ci signal reporting in the future.

cc @wojtek-t @deads2k @dgoodwin
