### ISSUE TITLE
Now that GCB is enabled, do humans need to be able to push to staging?

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#367]
How much do we increase trust if we say that the only way to get to staging is to have GCB push it?  Do we think there is ever a reason to have humans push except exceptional cases?

@tallclair @detiber

**Comment by cblecker** [comment]
I think we should leave that decision to the subprojects, IMO. They may want human backups, or workflows may demand other non-GCB methods.

I think defaulting to a strong recommendation for GCB-only might be good, and we could also set policies like "GCB-only access for the k/k core staging buckets". I would also say the prod bucket should be "bot only; humans in temporary break-fix scenarios".

**Comment by cblecker** [comment]
I basically don't want to get in the way of subprojects if there isn't a necessity to. I'd rather lure them with the carrot of "look at this super awesome secure way of doing things"

**Comment by thockin** [comment]
I mostly agree.  I am looking at it from prodsec or supply-chain security
POV.  Taking strong default positions with limited exceptional cases seems
ideal, if we can pull it off.

**Comment by cblecker** [comment]
Totally. And for core things (kube-cross, pause, etc) I think we can take a strict stance. A compromise in those images has the ability to impact ~all kubernetes deployments.

Things that are outside of core, if we make it too inflexible, then we may not be able to get them to adopt our solution in the first place. They'll just push to dockerhub or quay or whatever.

Theoretically speaking though, I support the automation-only, gitops approach. The more folks we get on board with that, the better.

**Comment by detiber** [comment]
I'm torn on this a bit, especially since we are talking about only the staging buckets here and not the prod buckets.

If we do restrict things down to only allowing GCB to push staging images it will make adoption a bit harder, especially since the actual build and push steps that are run in GCB are determined per-project, which means that new projects that hit issues will not have a way to replicate the steps locally and would lean on wg-k8s-infra to help with any debugging or issues. At the scale we've done so far that's not an issue, but it's not likely to scale well.

It's also reassuring from a project perspective to have a manual escape hatch in the event that the automation is broken, and that potential breakfix or security fixes wouldn't potentially be delayed in the event that the automation isn't working during an inconvenient time. This is already a bit of a concern with the image-promoter, but trying to troubleshoot GCB builds involves more moving parts than requesting a prow job just be rerun.

My preference would be to keep things as they are for now, and reassess the state of the world at a later point.

On Sep 14, 2019 12:32 AM, Christoph Blecker <notifications@github.com> wrote:

Totally. And for core things (kube-cross, pause, etc) I think we can take a strict stance. A compromise in those images has the ability to impact ~all kubernetes deployments.

Things that are outside of core, if we make it too inflexible, then we may not be able to get them to adopt our solution in the first place. They'll just push to dockerhub or quay or whatever.

Theoretically speaking though, I support the automation-only, gitops approach. The more folks we get on board with that, the better.

**Comment by thockin** [comment]
On Sat, Sep 14, 2019, 9:52 AM Jason DeTiberus <notifications@github.com>
wrote:

> I'm torn on this a bit, especially since we are talking about only the
> staging buckets here and not the prod buckets.
>
> If we do restrict things down to only allowing GCB to push staging images
> it will make adoption a bit harder, especially since the actual build and
> push steps that are run in GCB are determined per-project, which means that
> new projects that hit issues will not have a way to replicate the steps
> locally and would lean on wg-k8s-infra to help with any debugging or
> issues. At the scale we've done so far that's not an issue, but it's not
> likely to scale well.
>

Nothing will incentivize automation than this worst-case... ;)


> It's also reassuring from a project perspective to have a manual escape
> hatch in the event that the automation is broken, and that potential
> breakfix or security fixes wouldn't potentially be delayed in the event
> that the automation isn't working during an inconvenient time. This is
> already a bit of a concern with the image-promoter, but trying to
> troubleshoot GCB builds involves more moving parts than requesting a prow
> job just be rerun.
>

We do have break-glass.  There's a whole group of people who have direct
access to all stagings.  If break-glass is an exceptional case, escalation
seems appropriate.

More importantly, though, is supply-chain integrity.  Today I have zero
confidence that an image pushed to prod via promoter is built from
checked-in code, not subject to a local compromise (e.g. compiler hack),
etc.

If achieving that integrity requires making exceptional cases a bit more
painful (and I am not sure it does, but IF), I think I'd be OK with that.

That said, starting with an opt-in seems fair.  Pushing quickly to opt-out
seems like a good move.  Maybe we don't make it to mandatory for a while.

**Comment by thockin** [comment]
Would cluster-api projects volunteer to try this?  Only GCB for pushing,
with an escalation path to humans if/when needed?  Even the escalation path
is not well audited, but that can be a different project :)

**Comment by tallclair** [comment]
Agree with @thockin. If we leave per-project opt-in, can we ensure that:
1. Core (however we define that) images are all opted in
2. A project that is not opted in cannot promote images to a project that is opted in. I.e. opting in guarantees that promoted images for that project are built through GCB

**Comment by detiber** [comment]
/remove-lifecycle stale

I believe we are still working on identifying a way to trigger a post-submit job on tag creation.
/cc @ncdc

**Comment by ncdc** [comment]
I asked about how to match tag refs in #sig-testing [here](https://kubernetes.slack.com/archives/C09QZ4DQB/p1572547611010400). Copying @Katharine's response here:

> If you have a tag/branch naming scheme you can use a regex to distinguish
e.g. set branches to ^v\d+.\d+(.\d+)?$ to only match version tags or something.
there isn't really a good way to do this, though we have discussed it

I am 💯 interested in automating tag builds. If anyone is available to work with me on this, please let me know.

**Comment by ncdc** [comment]
Is the thinking that when a tag is pushed, that would directly trigger GCB, or do you think the flow is Prow -> GCB?

**Comment by detiber** [comment]
> Is the thinking that when a tag is pushed, that would directly trigger GCB, or do you think the flow is Prow -> GCB?

I think either approach would work, but if we trigger the GCB build based on the tag directly, we might need to make sure that the GCB build output is published somewhere that is more visible than it is today.

**Comment by ncdc** [comment]
Gotcha. I have time to work on this, so if someone can point me in a direction, I'm happy to get started.

**Comment by Katharine** [comment]
I would first question whether we need to tag images in staging at all.
Staging tags should be fairly meaningless, with the tags in production
buckets being the important ones. The image promoter can apply tags that do
not match the ones in the bucket it promotes from. This is how I originally
envisioned it — take an image tagged with a commit hash from staging and
promote it to a numbered version in production.

However, if for some reason you must do this, one imagined approach here is
that you would use prow to trigger GCB in a similar manner to how the
existing jobs are triggered.

One of the prow environment variables should tell you which tag was pushed,
though I’m not certain which. Once you know this, you can pass it through
from prow to GCB by passing it through using --env-passthrough=WHATEVER

**Comment by ncdc** [comment]
I don't believe we're currently doing this in Cluster API today (I'll have to double check), but with previous projects, we've logged the version when starting the app. If we're doing this/start doing this, I would expect an image with tag vX.Y.Z would show that version string in the log, and that is only the case if we build from a proper git tag.

Are we talking about two different types of tags - image tags vs git tags?

**Comment by detiber** [comment]
So, we don't necessarily need a specifically tagged image in the staging bucket, but what we ideally do need is the following:
- We initiate a release by tagging the git repo with the version tag
- We can match up a specific image build that was built in GCB and pushed to the staging repository to the exact commit hash that is associated with the git tag

Today we do post-submit builds to staging for each branch, but that assumes the last merge to a branch was successful and that the tag pushed exactly matches the current state of the associated branch. I'm not sure that this can be assumed to be the case for all releases of all projects that are using image promotion.

> However, if for some reason you must do this, one imagined approach here is
that you would use prow to trigger GCB in a similar manner to how the
existing jobs are triggered.

I believe the problem is that currently prow isn't able to trigger based on a tag, only on branches.

**Comment by Katharine** [comment]
> One of the prow environment variables should tell you which tag was pushed,
though I’m not certain which. Once you know this, you can pass it through
from prow to GCB by passing it through using --env-passthrough=WHATEVER

Ignore this part, I forgot how it works (in my defence, I am on vacation and this is the first thing I wrote after waking up).

> I believe the problem is that currently prow isn't able to trigger based on a tag, only on branches.

Prow _will_ run a post submit when you push a branch unless the branch filter prevents it from doing so. As such, with no filter, if you pushed a tag `v2.0`, and you did not have a `branches` filter that prohibited it, a job would run. That job would build the image with `git describe` returning `v2.0`, which seems likely to cause whatever internal automatic tagging you have to also return `v2.0`. The image would then be tagged `v20191216-v2.0`, or similar (because the value of `_GIT_TAG` is based on `git describe` prefixed with the date.

I think this already meets your requirements with no change, assuming you do not filter the `branches` field.

**Comment by ncdc** [comment]
Right now we restrict the branches for image building to `master` and `release-0.2` (https://github.com/kubernetes/test-infra/blob/d6906fc77dfb17c7723393d3a52a78f7f3dd9b7f/config/jobs/image-pushing/k8s-staging-cluster-api.yaml#L10-L12). If we expand that to `vX.Y.Z`, is that sufficient for building an image from a semver tag? I think so, since our cloudbuild file runs `make release-staging`... right?

**Comment by detiber** [comment]
@ncdc I *believe* so

**Comment by ncdc** [comment]
I just opened https://github.com/kubernetes/test-infra/pull/15624 to see about building and pushing semver tags to staging for 3 Cluster API repos.

**Comment by detiber** [comment]
kubernetes-sigs/cluster-api and kubernetes-sigs/cluster-api-provider-aws no longer require manual pushing to staging. I cannot speak for the other cluster-api related projects at this time, though
