### ISSUE TITLE
Move Velodrome from old Google-only cluster to aaa

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#505]
@apelisse I assume we actually need to move it, yes?

Assuming so:

1) PR to make a group and namespace

2) Load YAML

3) testng

4) flip DNS

5) turn down old

**Comment by apelisse** [comment]
To be honest, I don't know what's going on with Velodrome and how it's use nowadays. @cjwagner ?

**Comment by apelisse** [comment]
Also, you're missing the complicated part: migrate the data from PVs, since it has TSDBs. It also has a mysql database from Google Cloud SQL.

**Comment by thockin** [comment]
Well, SOMEONE will have to move it.  We're going to put a clock on the old
cluster and shut it down in Q1 or Q2 at worst

**Comment by cjwagner** [comment]
We've been having problems with velodrome and we've been slowly replacing the parts we use with https://monitoring.prow.k8s.io.

Do we need the mysql DB or any of the GitHub data transformation and related metrics? I don't see any graphs that use it and I think that https://k8s.devstats.cncf.io covers GitHub metrics.

The bigquery metric data will need to be moved to a new influxdb instance and the bigquery metric job will need to be updated to push that. Can persistent disks be moved between GCP projects?

**Comment by thockin** [comment]
> The bigquery metric data will need to be moved to a new influxdb instance and
> the bigquery metric job will need to be updated to push that. Can persistent disks
> be moved between GCP projects?

Not that I am aware of.

**Comment by apelisse** [comment]
> The bigquery metric data will need to be moved to a new influxdb instance and the bigquery metric job will need to be updated to push that. Can persistent disks be moved between GCP projects?

How much data (duration) does it retain? O(weeks) or O(days)? the latter wouldn't require any migration.

**Comment by thockin** [comment]
@apelisse @cjwagner 

Please consider this a formal request to start thinking about what, if anything, you need to migrate regarding velodrome.

It is one of 2 projects left in the google-only "utilicluster".  If it is still serving a purpose, we need a plan to move to the newer, community-owned "aaa" cluster.  The YAML and associated things are NOT in the k8s.io repo, so I can not offer any guidance yet.

If velodrome is defunct, I'll be happy to turn it down for you.

**Comment by apelisse** [comment]
I'll look at it now, see what's used and what's not.

**Comment by apelisse** [comment]
https://github.com/kubernetes/test-infra/pull/16383

**Comment by cjwagner** [comment]
cc @Katharine who has been auditing the security and looking into what is used and by what

**Comment by Katharine** [comment]
The yaml, and scripts to turn the yaml into usable yaml, are in test-infra: https://github.com/kubernetes/test-infra/tree/master/velodrome

Having asked Istio engprod, they claim they still care about their deployment, perhaps including their github metrics — so deleting all of that doesn't seem ideal without further discussion. Is cleaning up the non-Kubernetes uses of this a requirement? We almost certainly _don't_ want to move those into aaa, being not-Kubernetes.

As for our current usage, we primarily care about the test health dashboards, e.g. http://velodrome.k8s.io/dashboard/db/job-health-merge-blocking?orgId=1 (cc @spiffxp)

For those as configured today (to my knowledge) we only need grafana and influxdb, with influxdb exposed publicly because there is a prowjob that writes directly to it. The rest is now unnecessary.

The setup also has significant reliability and availability issues, so it is not clear whether we really want to carry the current configuration around, but it is unlikely anyone will have time to look at redoing that more significantly until Q2, so if we want to move before then it will have to be transposing  (a subset of) the existing setup.

**Comment by Katharine** [comment]
Also — given the evolution of velodrome in the last few years, we'll take over responsibility from @apelisse for the future of velodrome, whether that be migrate, replace, and/or turn down.

cc @amwat @BenTheElder

**Comment by thockin** [comment]
On Thu, Feb 20, 2020 at 12:23 PM Katharine Berry
<notifications@github.com> wrote:
>
> The yaml, and scripts to turn the yaml into usable yaml, are in test-infra: https://github.com/kubernetes/test-infra/tree/master/velodrome
>
> Having asked Istio engprod, they claim they still care about their deployment, perhaps including their github metrics — so deleting all of that doesn't seem ideal without further discussion. Is cleaning up the non-Kubernetes uses of this a requirement? We almost certainly don't want to move those into aaa, being not-Kubernetes.

Yes, you don't want to move non-k8s stuff into aaa.  I was hoping to
turn off the cluster, which lives in "kubernetes-site" project.  If
you want to take it over once everyone else has left, I am happy to
hand it over.

**Comment by thockin** [comment]
Hi Katharine,

Have you had any chance to think about this?

**Comment by BenTheElder** [comment]
velodrome was shut down IIRC
/assign @spiffxp
