### ISSUE TITLE
Add repo labels (area/) for different components

### ISSUE THREAD

**Issue by munnerz** [kubernetes/k8s.io#508]
It was suggested that we use labels to denote issues by their area - Prow supports `area/` labels for this, and there already exists one label that can be used as an example (`area/dns`): https://github.com/kubernetes/test-infra/blob/6baeb3d9949b9e6d9404dd3b4a6b28392de68ee0/label_sync/labels.yaml#L803-L810

These can then be set by commenting, for example: `/area dns`.

We should collate a list of labels here for the initial PR, and in future we can PR more directly into the labelsync config. A few to start:

* `area/velodrome`
* `area/cert-manager`
* `area/gcsweb`
* `area/publishing-bot`
* `area/boskos`

A few more general ones that may be useful:

* `area/monitoring`
* `area/reliability`

We should write up descriptions for some of these bits too.

**Comment by rikatz** [comment]
Based in #437:

* area/aaa (or area/cluster)
* area/auditing
* area/site

Will think in some other areas :)

**Comment by justaugustus** [comment]
It may useful to further scope the labels e.g., `area/infra/**`

**Comment by spiffxp** [comment]
/remove-lifecycle rotten

Here's what we have:
- area/access
- area/artifacts
- area/billing
- area/cluster-infra
- area/cluster-mgmt
- area/dns
- area/infra/auditing
- area/infra/cert-manager
- area/infra/monitoring
- area/infra/publishing-bot
- area/infra/reliability

Synced via: https://github.com/kubernetes/test-infra/blob/c9d7d82dca1c4966db01d732ea942022da838ac2/label_sync/labels.yaml#L831-L897

I don't particularly enjoy this list, because some of it is cross-cutting concerns, and some of it corresponds to specific directories.

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/milestone v1.21
I can take another crack at this, or I'm open to suggestions from others

**Comment by spiffxp** [comment]
/reopen
and I forgot to reopen...

**Comment by spiffxp** [comment]
Mentioned this during last weeks meeting. I feel like this is a proxy for how we think about, model and organize our work.  We've got debt to pay down to make it easier to manage and onboard. So it's more important than "eh they're just labels"

I feel like we should have one set for currently running apps or services. Things like dns, k8s.gcr.io for services. Things like triage-party, slack-infra, publishing-bot for apps (things running in aaa). 

There are cross-cutting apps/services that span infra and folders (eg prow, staging repos)

There are also cross-cutting concerns like authentication, authorization, auditability, observability etc

An alternative approach used by test-infra is to map area labels to folder structure. This would require shuffling of code to get to desired labelset. Or we could start by making labels that align to folders we have today

**Comment by spiffxp** [comment]
Here's what we have:
- `area/access`
- `area/artifacts`
- `area/billing`
- `area/cluster-infra`
- `area/cluster-mgmt`
- `area/dns`
- `area/infra/auditing`
- `area/infra/cert-manager`
- `area/infra/monitoring`
- `area/infra/publishing-bot`
- `area/infra/reliability`
- `area/infra/terraform`
- `area/prow`
- `area/release-eng`

Here's what I propose:
- drop `area/infra/reliability`, `area/infra/monitoring`, `area/access`
- keep releng labels `area/artifacts`, `area/release-eng`
- add `area/apps` for issues related to apps in general, migrate `area/cluster-infra`
- add `area/apps/{foo}` for `apps/{foo}` (migrate `area/infra/publishing-bot`, `area/infra/cert-manager`)
- add `area/infra` for `infra/gcp/*` (and issues related to infra in general, migrate `area/cluster-mgmt`)
- add `area/terraform` for `infra/gcp/clusters/*` (and issues/PRs related to terraform in general, migrate `area/infra/terraform`)
- add `area/bash` for `infra/gcp/clusters/*.sh` (and issues/PRs related to "the bash scripts" in general)
- add `area/k8s.gcr.io` for `k8s.gcr.io/*`
- add `area/audit` for `audit/*` (and issues related to auditing)
- add `area/policy` for `policies/*` (and issues related to policy formation/decisions, like what should (not) be allowed)
- if I didn't mention it, keep it

Leaving us with:
- `area/apps`
- `area/apps/cert-manager`
- `area/apps/gcsweb`
- `area/apps/k8s-io`
- `area/apps/kubernetes-external-secrets`
- `area/apps/node-perf-dash`
- `area/apps/perfdash`
- `area/apps/prow`
- `area/apps/publishing-bot`
- `area/apps/sippy`
- `area/apps/slack-infra`
- `area/apps/triageparty-release`
- `area/artifacts`
- `area/audit`
- `area/bash`
- `area/billing`
- `area/dns`
- `area/infra`
- `area/k8s.gcr.io`
- `area/policy`
- `area/prow`
- `area/release-eng`
- `area/terraform`

Or in patch form:
```diff
@@ -1,14 +1,23 @@
-- area/access
+- area/apps
+- area/apps/cert-manager
+- area/apps/gcsweb
+- area/apps/k8s-io
+- area/apps/kubernetes-external-secrets
+- area/apps/node-perf-dash
+- area/apps/perfdash
+- area/apps/prow
+- area/apps/publishing-bot
+- area/apps/sippy
+- area/apps/slack-infra
+- area/apps/triageparty-release
 - area/artifacts
+- area/audit
+- area/bash
 - area/billing
-- area/cluster-infra
-- area/cluster-mgmt
 - area/dns
-- area/infra/auditing
-- area/infra/cert-manager
-- area/infra/monitoring
-- area/infra/publishing-bot
-- area/infra/reliability
-- area/infra/terraform
+- area/infra
+- area/k8s.gcr.io
+- area/policy
 - area/prow
 - area/release-eng
+- area/terraform
```

**Comment by spiffxp** [comment]
**Why both `area/apps/prow` and `area/prow`?**

One is about the specific app or set of resources deployed on aaa

The other is about all prow concerns in general, include the build clusters, migrating prow jobs, etc

**Why drop everything out of `area/infra/foo`?**

Conceptually, `area/apps/foo` maps directly to the files/app in `apps/foo`.  The same can't be said for the `area/infra/foo`.  We could move high-level "infra" or "services" into infra, but since `dns/` and especially `k8s.gcr.io/` get so much traffic where they are, I'd rather not relocate until we know for sure where they're going.  And how to organize our infra config / scripts beyond "put them all in infra" is not obvious to me right now.

I considered `area/infra/gcp`, but we can use `area/provider/gcp` and other `area/provider/foo` labels if we need to talk about other cloud providers (and if we find that ends up conflating things, we'll migrate then...)

**Comment by spiffxp** [comment]
I've opened https://github.com/kubernetes/test-infra/pull/23084 to implement the above

**Comment by spiffxp** [comment]
/close

Calling this done, now that the following have merged:
- setting up the labels: https://github.com/kubernetes/test-infra/pull/23084
- adding them to OWNERS files: https://github.com/kubernetes/k8s.io/pull/2444
