### ISSUE TITLE
Parity between clusters secrets

### ISSUE THREAD

**Issue by rjsadow** [kubernetes/k8s.io#5734]
I'm working on migrating many of the prow jobs from the default GCP cluster to the community clusters (primarily EKS) https://github.com/kubernetes/test-infra/issues/29722. Generally speaking we've avoided transitioning jobs that reference any type of secrets in their manifest out of uncertainty whether or not an equivalent secret will be on the target cluster. To help this effort, could I get a list of the names of secrets that are available on `eks-prow-build-cluster` and `k8s-infra-prow-build`? I understand the sensitive nature of some of these secrets and I'm not asking for the values or any content inside them, just the names. This will help our effort better understand what jobs can easily be migrated to the different clusters.

**Comment by BenTheElder** [comment]
> Generally speaking we've avoided transitioning jobs that reference any type of secrets in their manifest out of uncertainty whether or not an equivalent secret will be on the target cluster. To help this effort, could I get a list of the names of secrets that are available on each cluster? I understand the sensitive nature of some of these secrets and I'm not asking for the values or any content inside them, just the names. This will help our effort better understand what jobs can easily be migrated to the different clusters.

The names of the secrets referenced are inherently listed in the public CI configuration as-is, with no need to dump them from the clusters.

**Comment by rjsadow** [comment]
When you say in the public CI configuration, what are you referring to? The k/test-infra jobs?

**Comment by BenTheElder** [comment]
Right, the config in git in test-infra.

**Comment by rjsadow** [comment]
So, my concern is more geared towards understanding the differences between the clusters.  I know I can see (for instance) [`postsubmit-node-feature-discovery-e2e-test` ](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/node-feature-discovery/node-feature-discovery-postsubmits.yaml#L24) uses the `node-feature-discovery-ci` secret in the default cluster. But don't have any way of understanding if that same secret is available on the community clusters to migrate it. Does that make sense?

**Comment by BenTheElder** [comment]
> So, my concern is more geared towards understanding the differences between the clusters. I know I can see (for instance) [postsubmit-node-feature-discovery-e2e-test ](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/node-feature-discovery/node-feature-discovery-postsubmits.yaml#L24)uses the node-feature-discovery-ci secret in the default cluster. But don't have any way of understanding if that same secret is available on the community clusters to migrate it. Does that make sense?

I see.

Broadly speaking, secrets have only been created in the new clusters if we can create something using purely community resources. There are no identical secrets, but there are secrets with the same name.

For anything that would've been created with community resources, the backing resources would have been created here.

A crude answer: Attempting a migrated copy version of _one_ job using any secret not yet used in that cluster will make that apparent.

Otherwise I'd say we still don't need a list of secrets in _all_ clusters, what you need is a list of secrets *in the two community clusters* to know if they exist there yet, the list in the legacy clusters is ~irrelevant, because they only matter if a job references them anyhow.

You could dump a list from a CI job. I don't think any one person is on hand with access to all of the clusters to go dump this.

**Comment by rjsadow** [comment]
> what you need is a list of secrets _in the two community clusters_ to know if they exist there yet

Yes! That's very fair to say. I'll amend the issue to specify only for the two community clusters.

**Comment by ameukam** [comment]
I don't think we want credentials parity between community clusters. For historical reasons, the `default` cluster kept most of them to provide a simple way to run those jobs. We probably want to rethink this strategy and focus on using short live tokens for authencation to the environments we use.
