### ISSUE TITLE
Assign public IP addresses to nodes in EKS Prow build cluster

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/k8s.io#5759]
All nodes in the EKS Prow build cluster only have private IP addresses assigned. All traffic to the Internet is going via NAT and Internet Gateways. This is very limited because all nodes are using a single IP address to reach out to external services like Docker Hub, GitHub, and more. All these services have strict rate limits, and we've started frequently reaching these rate limits.

As a way to mitigate this, I propose trying to replace NAT Gateway by assigning a public IP address to each node. We already do this in the GKE cluster, so it should be fine to do the same in the EKS cluster.

Prerequisites:

- Ensure that it's possible to make this change without recreating the cluster
- Ensure that proper Security Groups are in place to block external access to nodes

/sig k8s-infra
/assign
/priority critical-urgent
cc @dims @ameukam @pkprzekwas

**Comment by MadhavJivrajani** [comment]
Just xposting so that there's full context.

+1 to this issue. However I do think that we should also be creating a read-only common GH token for projects to use, specifically for read heavy jobs such as those run by projects like CAPI, which have run into the rate limit issue even on GKE clusters (ref https://github.com/kubernetes/org/issues/4165).

xref slack thread: https://kubernetes.slack.com/archives/C01672LSZL0/p1693217649633179?thread_ts=1692945837.121219&cid=C01672LSZL0

**Comment by xmudrii** [comment]
This is done.
/close
