### ISSUE TITLE
https://pkgs.k8s.io/ does not support ipv6

### ISSUE THREAD

**Issue by Martin-Luther** [kubernetes/k8s.io#6820]
The following command generates `curl: (22) The requested URL returned error: 403`

```tty
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
```

**Comment by Martin-Luther** [comment]
Hello,
After more investigations, it seems like my provider gave me IPv6 addresses that were blocked by GCP. So I could only use IPv4. 
I have tried with another provider, and things worked just fine with IPv6.
Let's say that someone in the same situation finds this ticket; is it possible to say to Kubeadmn, Kubelet & Kubectl to fallback to IPv4 when IPv6 fails ?

**Comment by xmudrii** [comment]
@Martin-Luther What cloud provider are you using? We have been observing blocked IP addresses from Hetzner; are you using Hetzner by any chance?

**Comment by Martin-Luther** [comment]
@xmudrii 
> @Martin-Luther What cloud provider are you using? We have been observing blocked IP addresses from Hetzner; are you using Hetzner by any chance?

As mentioned in my previous message : 

> After more investigations, it seems like my provider gave me IPv6 addresses that were blocked by GCP

I am @ Gandi, and seriously thinking about moving to Digital Ocean or Hostinger if they allow me o add additional volumes ...

**Comment by BenTheElder** [comment]
pkgs.k8s.io is currently hosted with a combination of GCP + AWS (like most, but not all of our infra), we have to work with what is available to us and major cloud providers do block some IPs for various reasons (e.g. US sanctions, abuse, ...).

If someone wanted to help provide a mirror, we could consider it, otherwise I recommend self-hosting a personal mirror (or obtaining hosting without IP reputation issues, or escalating to your hosting provider), it simply isn't scalable for us to follow up on these as a project and we don't have a viable alternative on hand for hosting, these vendors are providing a lot of resources to the project.

It seems the title of this issue is inaccurate?

**Comment by xmudrii** [comment]
Test on an AWS EC2 instance with IPv6 address and no public IPv4 address, works perfectly fine. Packages are installed without a problem, and I can see that the IPv6 address is used if curl `pkgs.k8s.io`.

Given that we have IPv6 support, I'm going to close this issue.
/close
